services:
  navidrome:
    environment:
      ND_CONFIGFILE: "/data/navidrome.toml"
    image: deluan/navidrome:latest
    pull_policy: always
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - /home/jonany/.cache/navidrome:/data
      - /home/jonany/media/audio:/music:ro
      - /home/jonany/.config/navidrome/config.toml:/data/navidrome.toml:ro
