services:
  navidrome:
    image: deluan/navidrome:latest
    pull_policy: always
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Artwork
      ND_ARTISTARTPRIORITY: "artist.*, album/artist.*"
      ND_COVERARTPRIORITY: "cover.*, folder.*, front.*, embedded"
      ND_ENABLECOVERANIMATION: false
      # Caching
      ND_ENABLEARTWORKPRECACHE: false
      ND_IMAGECACHESIZE: "0"
      ND_TRANSCODINGCACHESIZE: "0"
      # Features
      ND_ENABLESTARRATING: false
      # Playlists
      ND_AUTOIMPORTPLAYLISTS: true
      ND_DEFAULTPLAYLISTPUBLICVISIBILITY: true
      # Services
      ND_ENABLEEXTERNALSERVICES: false
      ND_LASTFM_ENABLED: false
      ND_LISTENBRAINZ_ENABLED: false
      # Etc
      #ND_LOGLEVEL: debug
    volumes:
      - /home/jonany/.cache/navidrome:/data
      - /home/jonany/media/audio:/music:ro
