services:
  navidrome:
    image: deluan/navidrome:latest
    pull_policy: always
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_ARTISTARTPRIORITY: "artist.*, album/artist.*"
      ND_AUTOIMPORTPLAYLISTS: false
      ND_COVERARTPRIORITY: "cover.*, folder.*, front.*, embedded"
      ND_ENABLEARTWORKPRECACHE: false
      ND_ENABLECOVERANIMATION: false
      ND_ENABLEEXTERNALSERVICES: false
      ND_ENABLESTARRATING: false
      ND_IMAGECACHESIZE: "0"
      ND_LASTFM_ENABLED: false
      ND_LISTENBRAINZ_ENABLED: false
      ND_TRANSCODINGCACHESIZE: "0"
    volumes:
      - /home/jonany/.cache/navidrome:/data
      - /home/jonany/media/audio/music:/music:ro
